# -*- coding: utf-8 -*-
"""DammFaltaMapa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aO8M03GIGMVRdVorHxD3TxqGhtQ1W3z7

# Damm Smart Truck — Demo 3 rutas Mollet/cercanías

Este notebook enlaza Hackaton.xlsx, ZM040.XLSX, Horarios Entrega.XLSX y Layout Mollet.xlsx para generar 3 demos con KPIs, planos 2D y 3D.
"""

!pip install -q pandas openpyxl plotly

"""## Código principal
Cambia `DEMO_ROUTES` para probar cualquier ruta/fecha.

"""

# -*- coding: utf-8 -*-
"""
Damm Smart Truck - Demo 3 rutas Mollet/cercanías
================================================
Este script enlaza:
- Hackaton.xlsx: pedidos/rutas/clientes/productos
- ZM040.XLSX: pesos, volúmenes, dimensiones, unidad logística
- Horarios Entrega.XLSX: ventanas horarias y cierres
- Layout Mollet.xlsx: contexto opcional de layout de almacén

y genera para 3 rutas-demo:
- secuencia optimizada de clientes
- asignación de carga a camión 6 palets x 12 filas x 6 columnas x 5 alturas
- KPIs de carga
- plano 2D HTML
- plano 3D HTML

El algoritmo funciona para cualquier ruta/fecha cambiando DEMO_ROUTES.
"""

from pathlib import Path
import pandas as pd
import numpy as np
import plotly.graph_objects as go

DATA_DIR = Path('.')
OUTPUT_DIR = Path('demo_damm_3_rutas')
OUTPUT_DIR.mkdir(exist_ok=True)

DEMO_ROUTES = [
    # Ruta muy centrada en Mollet/Mollet del Vallès
    {"fecha": "2026-03-04", "ruta": "DR0006", "label": "Demo A - Mollet"},
    # Ruta Mollet / Granollers
    {"fecha": "2026-03-11", "ruta": "DR0017", "label": "Demo B - Mollet / Granollers"},
    # Ruta Canovelles / Granollers, zona próxima
    {"fecha": "2026-03-30", "ruta": "DR0038", "label": "Demo C - Granollers / Canovelles"},
]

MOLLET_KEYWORDS = [
    'MOLLET','MONTMELO','MONTMELÓ','PARETS','GRANOLLERS','MARTORELLES',
    'SANTA PERPETUA','LLIÇA','LLIÇÀ','LA LLAGOSTA','SANT FOST','VALLROMANES','CANOVELLES'
]

TRUCK = {
    'rows': 12,
    'cols': 6,
    'levels': 5,
    'base_cells': 72,
    'total_positions': 360,
    'column_priority': [1, 6, 2, 5, 3, 4],
}

COLOR_BY_TYPE = {
    'caja': '#d71920',
    'barril': '#555555',
    'retornable': '#8c564b',
    'unidad': '#9467bd',
    'otros': '#1f77b4',
}


def norm(x):
    if pd.isna(x):
        return ''
    return str(x).strip().upper()


def read_data(data_dir=DATA_DIR):
    deliveries = pd.read_excel(data_dir/'Hackaton.xlsx', sheet_name='Detalle entrega', engine='openpyxl')
    materials = pd.read_excel(data_dir/'ZM040.XLSX', sheet_name='Sheet1', engine='openpyxl')
    horarios = pd.read_excel(data_dir/'Horarios Entrega.XLSX', sheet_name='Sheet1', engine='openpyxl')
    try:
        zubic = pd.read_excel(data_dir/'Hackaton.xlsx', sheet_name='Materiales zubic', engine='openpyxl')
    except Exception:
        zubic = pd.DataFrame()
    return deliveries, materials, horarios, zubic


def prepare_material_master(materials):
    mat = materials.copy()
    mat['Material'] = mat['Material'].astype(str).str.strip()
    mat['UMA'] = mat['UMA'].astype(str).str.strip()
    for c in ['Longitud','Ancho','Altura','Volumen','Peso bruto','Peso neto','Contador','Denom.']:
        if c in mat.columns:
            mat[c] = pd.to_numeric(mat[c], errors='ignore')
    # Preferimos unidad exacta de venta; fallback más adelante.
    keep = ['Material','UMA','Contador','Denom.','Longitud','Ancho','Altura','Volumen','UV','Peso bruto','Peso neto','Jquía.productos']
    keep = [c for c in keep if c in mat.columns]
    return mat[keep].drop_duplicates(['Material','UMA'])


def add_material_info(route_df, mat):
    df = route_df.copy()
    df['Material_norm'] = df['Material'].astype(str).str.strip()
    df['Unidad_norm'] = df['Un.medida venta'].astype(str).str.strip()
    out = df.merge(
        mat,
        left_on=['Material_norm','Unidad_norm'],
        right_on=['Material','UMA'],
        how='left',
        suffixes=('', '_mat')
    )
    # fallback por material, usando preferencia CAJ, BRL, UN, BOT, PAL
    missing = out['Peso bruto'].isna() if 'Peso bruto' in out.columns else pd.Series(False, index=out.index)
    if missing.any():
        mat2 = mat.copy()
        pref = {'CAJ':0,'BRL':1,'UN':2,'BOT':3,'PAK':4,'PAL':5}
        mat2['pref'] = mat2['UMA'].map(pref).fillna(9)
        fallback = mat2.sort_values('pref').drop_duplicates('Material')
        fb = out.loc[missing, ['Material_norm']].merge(fallback, left_on='Material_norm', right_on='Material', how='left', suffixes=('','_fb'))
        for c in ['UMA','Contador','Denom.','Longitud','Ancho','Altura','Volumen','UV','Peso bruto','Peso neto','Jquía.productos']:
            if c in out.columns and c in fb.columns:
                out.loc[missing, c] = fb[c].values
    return out


def detect_product_type(row):
    text = f"{norm(row.get('Material_norm',''))} {norm(row.get('Denominación',''))} {norm(row.get('Unidad_norm',''))} {norm(row.get('UMA',''))}"
    if any(k in text for k in ['VACIO','VACÍO','RETORNO','ENV','CJ13V','CJ12V','BRL30V','BRL20V']):
        return 'retornable'
    if any(k in text for k in ['BRL','BARRIL','BIDON','BIDÓN']):
        return 'barril'
    if any(k in text for k in ['CAJ','CAJA','BOT','PAK','LAT']):
        return 'caja'
    return 'unidad'


def unit_cells(product_type):
    # MVP: barril/bidón ocupa doble celda; retornable/caja/unidad ocupan 1.
    return 2 if product_type == 'barril' else 1


def prepare_horarios(horarios):
    h = horarios.copy()
    h['cliente_key'] = h['Deudor'].astype(str).str.replace('.0','', regex=False).str.strip()
    # convertir decimal a HH:MM
    def dec_to_time(x):
        try:
            if pd.isna(x): return ''
            if isinstance(x, str) and ':' in x: return x
            v=float(x)
            if v <= 0: return ''
            mins = int(round(v*24*60))
            return f"{mins//60:02d}:{mins%60:02d}"
        except Exception:
            return ''
    h['hora_inicio'] = h['Horario inicia a'].apply(dec_to_time)
    h['hora_fin'] = h['Horario termina a'].apply(dec_to_time)
    h['cerrado'] = h['Cierre Si/No'].astype(str).str.upper().eq('X')
    return h


def build_route_dataset(deliveries, mat, horarios, zubic, fecha, ruta):
    df = deliveries.copy()
    df['FECHA_dt'] = pd.to_datetime(df['FECHA'], errors='coerce')
    df['FECHA_str'] = df['FECHA_dt'].dt.strftime('%Y-%m-%d')
    df['Ruta'] = df['Ruta'].astype(str).str.strip()
    df['Población'] = df['Población'].astype(str).str.strip()
    route = df[(df['FECHA_str'] == fecha) & (df['Ruta'] == ruta)].copy()
    # Para demo Mollet/cercanías: si ruta contiene mezcla, priorizamos poblaciones cercanas
    near_mask = route['Población'].str.upper().apply(lambda s: any(k in s for k in MOLLET_KEYWORDS))
    if near_mask.any():
        route = route[near_mask].copy()

    if route.empty:
        raise ValueError(f'No hay datos para {ruta} {fecha}')

    route = add_material_info(route, mat)
    route['cantidad'] = pd.to_numeric(route['Cantidad entrega'], errors='coerce').fillna(0).astype(int)
    route['tipo_producto'] = route.apply(detect_product_type, axis=1)
    route['cells_per_unit'] = route['tipo_producto'].apply(unit_cells)
    route['cells_needed'] = route['cantidad'] * route['cells_per_unit']
    route['peso_total'] = pd.to_numeric(route.get('Peso bruto', 0), errors='coerce').fillna(0) * route['cantidad']
    route['volumen_total'] = pd.to_numeric(route.get('Volumen', 0), errors='coerce').fillna(0) * route['cantidad']

    # Ubicación almacén opcional desde Materiales zubic
    if isinstance(zubic, pd.DataFrame) and not zubic.empty and 'Material' in zubic.columns:
        z = zubic.copy()
        z['Material'] = z['Material'].astype(str).str.strip()
        ubic_col = 'Ubic.' if 'Ubic.' in z.columns else None
        if ubic_col:
            route = route.merge(z[['Material', ubic_col]].drop_duplicates('Material'), left_on='Material_norm', right_on='Material', how='left', suffixes=('','_zubic'))
            route.rename(columns={ubic_col:'ubicacion_almacen'}, inplace=True)
    if 'ubicacion_almacen' not in route.columns:
        route['ubicacion_almacen'] = ''

    # Secuencia de clientes: ventana horaria primero si existe, luego CP/Población, luego entrega
    h = prepare_horarios(horarios)
    route['cliente_key'] = route['Destinatario mcía..1'].astype(str).str.replace('.0','', regex=False).str.strip()
    route['weekday'] = route['FECHA_dt'].dt.weekday + 1
    h_reduced = h[['cliente_key','Día semana','Turno','hora_inicio','hora_fin','cerrado']].drop_duplicates('cliente_key')
    route = route.merge(h_reduced, on='cliente_key', how='left')

    clients = route.groupby('cliente_key').agg(
        cliente_nombre=('Nombre 1','first'),
        poblacion=('Población','first'),
        cp=('CP','first'),
        entrega_min=('Entrega','min'),
        hora_inicio=('hora_inicio','first'),
        hora_fin=('hora_fin','first'),
        cerrado=('cerrado','first'),
        lineas=('Material','size'),
        piezas=('cantidad','sum'),
        peso=('peso_total','sum'),
        volumen=('volumen_total','sum')
    ).reset_index()
    clients['hora_inicio_sort'] = clients['hora_inicio'].replace('', '99:99').fillna('99:99')
    clients = clients.sort_values(['hora_inicio_sort','cp','poblacion','entrega_min']).reset_index(drop=True)
    clients['stop_order'] = np.arange(1, len(clients)+1)
    route = route.merge(clients[['cliente_key','stop_order']], on='cliente_key', how='left')
    route['microblock'] = ((route['stop_order']-1)//3)+1
    return route, clients


def build_positions():
    pos=[]; pref=1
    for col in TRUCK['column_priority']:
        for row in range(1, TRUCK['rows']+1):
            for level in range(TRUCK['levels'], 0, -1):
                pos.append({'fila':row,'columna':col,'altura':level,'preferencia':pref,'ocupado':False})
                pref+=1
    return pd.DataFrame(pos)


def expand_items(route):
    # Orden: paradas tempranas primero a posiciones más accesibles; dentro de parada, barril primero, luego cajas, retornables al final
    type_pref={'barril':0,'caja':1,'unidad':2,'retornable':3}
    rows=[]
    sorted_lines=route.copy()
    sorted_lines['type_pref']=sorted_lines['tipo_producto'].map(type_pref).fillna(9)
    sorted_lines=sorted_lines.sort_values(['stop_order','type_pref','Material_norm'])
    for _,r in sorted_lines.iterrows():
        # Limite práctico: expandimos por cantidad real, y luego la asignación cortará en 360 posiciones.
        for i in range(int(r['cantidad'])):
            rows.append({
                'pieza_id':f"{r['Entrega']}_{r['Material_norm']}_{i+1}",
                'cliente_key':r['cliente_key'],
                'cliente_nombre':r['Nombre 1'],
                'stop_order':int(r['stop_order']),
                'microblock':int(r['microblock']),
                'material':r['Material_norm'],
                'referencia':r['Material_norm'],
                'descripcion':r['Denominación'],
                'tipo_producto':r['tipo_producto'],
                'cells':int(r['cells_per_unit']),
                'peso':float(pd.to_numeric(r.get('Peso bruto',0), errors='coerce') or 0),
                'volumen':float(pd.to_numeric(r.get('Volumen',0), errors='coerce') or 0),
                'ubicacion_almacen':r.get('ubicacion_almacen','')
            })
    return pd.DataFrame(rows)


def assign_to_truck(items):
    positions=build_positions()
    assigned=[]; rejected=[]
    pos_i=0
    for _,item in items.iterrows():
        need=int(item['cells'])
        free_idx=positions.index[~positions['ocupado']].tolist()
        if len(free_idx) < need:
            rejected.append(item.to_dict()); continue
        chosen=free_idx[:need]
        # Ideal para barril: ocupar dos alturas/posiciones consecutivas accesibles; demo simplificada
        for idx in chosen:
            positions.at[idx,'ocupado']=True
            rec=item.to_dict()
            rec.update(positions.loc[idx, ['fila','columna','altura','preferencia']].to_dict())
            assigned.append(rec)
    return pd.DataFrame(assigned), positions, pd.DataFrame(rejected)


def make_2d(assign_df, title):
    # Vista superior: celda coloreada por tipo/producto de la posición más alta ocupada.
    if assign_df.empty:
        fig=go.Figure(); fig.update_layout(title=title); return fig
    top = assign_df.sort_values('altura', ascending=False).drop_duplicates(['fila','columna'])
    fig=go.Figure()
    central_gap=0.65; cell=1; pallet_gap=0.35
    def x_pos(c): return (c-1)*cell if c<=3 else (c-1)*cell+central_gap
    def y_pos(r): return ((r-1)//4)*(4*cell+pallet_gap)+((r-1)%4)*cell
    # palets background
    for block in range(3):
        y0=block*(4*cell+pallet_gap)
        for side in range(2):
            x0=0 if side==0 else 3*cell+central_gap
            pid=block*2+side+1
            fig.add_shape(type='rect',x0=x0-0.04,y0=y0-0.04,x1=x0+3*cell+0.04,y1=y0+4*cell+0.04,line=dict(color='#333',width=2),fillcolor='#fafafa',layer='below')
            fig.add_annotation(x=x0+1.5,y=y0-0.22,text=f'Palet {pid}',showarrow=False,font=dict(size=11))
    max_y=12*cell+2*pallet_gap
    fig.add_shape(type='rect',x0=3*cell,y0=-0.05,x1=3*cell+central_gap,y1=max_y-0.05,line=dict(color='#bbb',width=1,dash='dash'),fillcolor='#eee',layer='below')
    for _,r in top.iterrows():
        x0=x_pos(int(r['columna']))+0.05; y0=y_pos(int(r['fila']))+0.05
        color=COLOR_BY_TYPE.get(r['tipo_producto'],'#1f77b4')
        fig.add_shape(type='rect',x0=x0,y0=y0,x1=x0+0.9,y1=y0+0.9,line=dict(color='#111',width=1),fillcolor=color,opacity=0.88)
        fig.add_annotation(x=x0+0.45,y=y0+0.45,text=f"P{int(r['stop_order'])}<br>{str(r['material'])[:6]}",showarrow=False,font=dict(size=8,color='white'))
    fig.update_xaxes(range=[-0.7,7.6],showgrid=False,zeroline=False,title='Columnas')
    fig.update_yaxes(range=[max_y+0.8,-0.8],showgrid=False,zeroline=False,scaleanchor='x',scaleratio=1,title='Filas')
    fig.update_layout(title=title,width=1050,height=850,plot_bgcolor='white',showlegend=False,margin=dict(l=30,r=30,t=70,b=30))
    return fig


def make_3d(assign_df, positions, title):
    fig=go.Figure()
    if not assign_df.empty:
        colors=assign_df['tipo_producto'].map(COLOR_BY_TYPE).fillna('#1f77b4')
        text=("Cliente: "+assign_df['cliente_nombre'].astype(str)+
              "<br>Parada: "+assign_df['stop_order'].astype(str)+
              "<br>Material: "+assign_df['material'].astype(str)+
              "<br>Tipo: "+assign_df['tipo_producto'].astype(str)+
              "<br>Fila: "+assign_df['fila'].astype(str)+
              " Col: "+assign_df['columna'].astype(str)+
              " Alt: "+assign_df['altura'].astype(str))
        fig.add_trace(go.Scatter3d(x=assign_df['columna'],y=assign_df['fila'],z=assign_df['altura'],mode='markers',marker=dict(size=7,color=colors,opacity=0.9),text=text,hoverinfo='text',name='Carga asignada'))
    # remolque edges
    def line(x,y,z,color='black',width=5):
        fig.add_trace(go.Scatter3d(x=x,y=y,z=z,mode='lines',line=dict(width=width,color=color),hoverinfo='skip',showlegend=False))
    x0,x1=0.5,6.5; y0,y1=0.5,12.5; z0,z1=0.5,5.5
    for z in [z0,z1]:
        line([x0,x1],[y0,y0],[z,z]); line([x1,x1],[y0,y1],[z,z]); line([x1,x0],[y1,y1],[z,z]); line([x0,x0],[y1,y0],[z,z])
    for x,y in [(x0,y0),(x1,y0),(x1,y1),(x0,y1)]: line([x,x],[y,y],[z0,z1])
    for ysep in [4.5,8.5]: line([x0,x1],[ysep,ysep],[z0,z0],'gray',3); line([x0,x1],[ysep,ysep],[z1,z1],'gray',3)
    line([3.5,3.5],[y0,y1],[z0,z0],'lightgray',5); line([3.5,3.5],[y0,y1],[z1,z1],'lightgray',5)
    fig.add_trace(go.Scatter3d(x=[3.5],y=[-0.7],z=[1.2],mode='text',text=['CABINA<br>Fila 1'],textfont=dict(size=14,color='black'),hoverinfo='skip',showlegend=False))
    fig.add_trace(go.Scatter3d(x=[0.15],y=[6.5],z=[3],mode='text',text=['DESCARGA<br>LATERAL<br>COL 1'],textfont=dict(size=11,color='red'),hoverinfo='skip',showlegend=False))
    fig.add_trace(go.Scatter3d(x=[6.85],y=[6.5],z=[3],mode='text',text=['DESCARGA<br>LATERAL<br>COL 6'],textfont=dict(size=11,color='red'),hoverinfo='skip',showlegend=False))
    fig.update_layout(title=title,scene=dict(xaxis=dict(title='Columnas',range=[0,7.8],dtick=1),yaxis=dict(title='Filas',range=[-2,14],dtick=1),zaxis=dict(title='Altura',range=[0,6],dtick=1),aspectmode='manual',aspectratio=dict(x=1.1,y=2.2,z=0.8),camera=dict(eye=dict(x=1.6,y=-2.1,z=1.3))),width=1100,height=800,margin=dict(l=0,r=0,t=60,b=0))
    return fig


def kpis(route, clients, assign_df, rejected, label, fecha, ruta):
    return {
        'demo': label,
        'fecha': fecha,
        'ruta': ruta,
        'clientes': int(clients.shape[0]),
        'lineas_pedido': int(route.shape[0]),
        'piezas_pedido': int(route['cantidad'].sum()),
        'peso_total_estimado_kg': round(float(route['peso_total'].sum()),2),
        'volumen_total_estimado': round(float(route['volumen_total'].sum()),2),
        'posiciones_camion': TRUCK['total_positions'],
        'posiciones_ocupadas': int(assign_df.shape[0]),
        'ocupacion_pct': round(100*assign_df.shape[0]/TRUCK['total_positions'],2),
        'piezas_no_asignadas': int(rejected.shape[0]),
        'cajas_asignadas': int((assign_df['tipo_producto']=='caja').sum()) if not assign_df.empty else 0,
        'barriles_asignados': int((assign_df['tipo_producto']=='barril').sum()) if not assign_df.empty else 0,
        'retornables_asignados': int((assign_df['tipo_producto']=='retornable').sum()) if not assign_df.empty else 0,
    }


def recomendaciones(k):
    rec=[]
    rec.append('Cargar primero Zona C/R (últimas paradas y retornables) para que quede más al fondo.')
    rec.append('Dejar Zona A en columnas laterales 1 y 6 para descarga rápida de primeras paradas.')
    if k['barriles_asignados']>0: rec.append('Colocar barriles/bidones en posiciones accesibles y tratarlos como doble ocupación por peso/volumen.')
    if k['retornables_asignados']>0: rec.append('Reservar capacidad para retornables durante la ruta.')
    if k['piezas_no_asignadas']>0: rec.append('ALERTA: la ruta supera la capacidad visual del camión 6P; revisar fraccionamiento o vehículo mayor.')
    else: rec.append('OK: toda la carga demo cabe en la capacidad visual modelada.')
    return rec


def run_demo():
    deliveries, materials, horarios, zubic = read_data(DATA_DIR)
    mat = prepare_material_master(materials)
    all_kpis=[]
    excel_outputs={}
    for cfg in DEMO_ROUTES:
        fecha,ruta,label=cfg['fecha'],cfg['ruta'],cfg['label']
        route, clients = build_route_dataset(deliveries, mat, horarios, zubic, fecha, ruta)
        items = expand_items(route)
        assign_df, positions, rejected = assign_to_truck(items)
        kp = kpis(route, clients, assign_df, rejected, label, fecha, ruta)
        kp['recomendaciones'] = ' | '.join(recomendaciones(kp))
        all_kpis.append(kp)
        stem=f"{ruta}_{fecha}"
        # outputs
        route.to_csv(OUTPUT_DIR/f'{stem}_datos_enlazados.csv', index=False)
        clients.to_csv(OUTPUT_DIR/f'{stem}_secuencia_clientes.csv', index=False)
        assign_df.to_csv(OUTPUT_DIR/f'{stem}_asignacion_camion.csv', index=False)
        positions.to_csv(OUTPUT_DIR/f'{stem}_posiciones_camion.csv', index=False)
        rejected.to_csv(OUTPUT_DIR/f'{stem}_piezas_no_asignadas.csv', index=False)
        make_2d(assign_df, f'{label} - {ruta} {fecha} - Plano 2D').write_html(OUTPUT_DIR/f'{stem}_plano_2d.html')
        make_3d(assign_df, positions, f'{label} - {ruta} {fecha} - Plano 3D').write_html(OUTPUT_DIR/f'{stem}_plano_3d.html')
        excel_outputs[f'{stem}_clientes'] = clients
        excel_outputs[f'{stem}_kpi'] = pd.DataFrame([kp])
        print(f"Generado {stem}: clientes={kp['clientes']}, ocupación={kp['ocupacion_pct']}%, no asignadas={kp['piezas_no_asignadas']}")
    summary=pd.DataFrame(all_kpis)
    summary.to_csv(OUTPUT_DIR/'resumen_3_rutas_demo.csv', index=False)
    with pd.ExcelWriter(OUTPUT_DIR/'resumen_3_rutas_demo.xlsx', engine='openpyxl') as writer:
        summary.to_excel(writer, sheet_name='KPIs', index=False)
        for sh,df in excel_outputs.items():
            df.head(500).to_excel(writer, sheet_name=sh[:31], index=False)
    return summary

if __name__ == '__main__':
    summary = run_demo()
    print('\n=== RESUMEN 3 RUTAS ===')
    print(summary.to_string(index=False))

"""## Descargar resultados en Colab

"""

# En Colab, ejecuta esto para comprimir y descargar los resultados
import shutil, os
from google.colab import files
shutil.make_archive('demo_damm_3_rutas', 'zip', 'demo_damm_3_rutas')
files.download('demo_damm_3_rutas.zip')