# -*- coding: utf-8 -*-
"""MAPES_RUTES_PARADES.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AQFlU5jQeNhMTKR2ReaFuLjMHxnrl3Pg

# Damm Smart Truck — Parades agrupades experimental

Versió experimental basada en `MAPES_RUTES_COLAB`, però afegint agrupació de locals propers en una mateixa parada de camió. El radi per defecte és **100 metres** i el notebook compara automàticament `baseline` vs `clustered`.
"""

# MAPES_RUTES_CLUSTERING_COLAB - Damm Smart Truck
# Versió experimental: parades agrupades si locals estan propers.
# Necessita a Colab: Hackaton.xlsx, Horarios Entrega.XLSX. ZM040.XLSX opcional.

!pip install -q pandas openpyxl requests polyline plotly

from pathlib import Path
import time, math, hashlib, zipfile, warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import requests
import polyline
import plotly.graph_objects as go
from IPython.display import IFrame, display

# ==============================
# CONFIG
# ==============================
OUT = Path('mapes_rutes_cluster_output')
OUT.mkdir(exist_ok=True)

DEMO_ROUTES = [
    {"fecha": "2026-03-04", "ruta": "DR0006", "label": "Demo A - Mollet"},
    {"fecha": "2026-03-11", "ruta": "DR0017", "label": "Demo B - Mollet / Granollers"},
    {"fecha": "2026-03-30", "ruta": "DR0038", "label": "Demo C - Granollers / Canovelles"},
]

ORIGEN = {'lat': 41.5310, 'lng': 2.2325, 'nombre': 'DDI Fàbrica Mollet'}
NOMINATIM_URL = 'https://nominatim.openstreetmap.org/search'
USER_AGENT = 'DammSmartTruckHackathon/1.0 clustering-demo'
CACHE_FILE = OUT / 'clientes_latlng_cache.csv'

# Ruta / operativa
START_TIME_MIN = 7 * 60
AVG_SPEED_KMH = 25.0
PARKING_TIME_MIN = 3.0
SERVICE_PER_PIECE_MIN = 0.35
SERVICE_PER_LINE_MIN = 0.20
WALK_SPEED_M_PER_MIN = 80.0

# Clustering de parades
CLUSTER_RADIUS_M = 100      # radi recomanat per demo urbana
MAX_CLIENTS_PER_STOP = 3    # evita parades caminant massa grans
MAX_PIECES_PER_STOP = 80    # evita que una parada agrupada sigui inviable operativament
REQUIRE_TIME_WINDOW_OVERLAP = True

# Score Greedy
ALPHA_TRAVEL = 1.0
BETA_LATE = 12.0
GAMMA_URGENCY = 2.0
DELTA_SERVICE = 0.25

# Cost comparatiu baseline vs clustering
COST_DISTANCE = 1.0
COST_LATE = 15.0
COST_STOPS = 3.0       # penalitza cada parada del camió: aparcar/manobrar
COST_WALKING = 0.8     # penalitza temps caminant dins de parades agrupades

print('Configuració carregada. Radi clustering:', CLUSTER_RADIUS_M, 'm')

# ==============================
# UTILS
# ==============================
def clean_cp(cp):
    try:
        return str(int(float(cp))).zfill(5)
    except Exception:
        return str(cp).strip().zfill(5)


def parse_time_to_minutes(x, default=None):
    try:
        if pd.isna(x): return default
        if isinstance(x, str):
            txt=x.strip()
            if txt=='': return default
            if ':' in txt:
                h,m=txt.split(':')[:2]
                return int(h)*60+int(m)
            val=float(txt)
        else:
            val=float(x)
        if 0 < val < 1: return int(round(val*24*60))
        if val <= 24: return int(round(val*60))
        return int(round(val))
    except Exception:
        return default


def hhmm(m):
    if pd.isna(m): return ''
    m=int(round(m))
    return f'{(m//60)%24:02d}:{m%60:02d}'


def haversine_km(lat1, lon1, lat2, lon2):
    R=6371.0
    p1,p2=math.radians(lat1),math.radians(lat2)
    dp=math.radians(lat2-lat1)
    dl=math.radians(lon2-lon1)
    a=math.sin(dp/2)**2 + math.cos(p1)*math.cos(p2)*math.sin(dl/2)**2
    return 2*R*math.asin(math.sqrt(a))


def distance_m(a, b):
    return 1000*haversine_km(a['lat'], a['lng'], b['lat'], b['lng'])


def address_key(q):
    return hashlib.sha1(q.lower().encode('utf-8')).hexdigest()


def build_address(row):
    return f"{row['calle']}, {row['cp']}, {row['poblacion']}, Barcelona, España"


def travel_time_min(km):
    return km / AVG_SPEED_KMH * 60

# ==============================
# DATA
# ==============================
def load_files():
    missing=[f for f in ['Hackaton.xlsx','Horarios Entrega.XLSX'] if not Path(f).exists()]
    if missing:
        raise FileNotFoundError('Falten fitxers: '+', '.join(missing)+'. Puja-los al panell Files de Colab.')
    deliveries=pd.read_excel('Hackaton.xlsx', sheet_name='Detalle entrega', engine='openpyxl')
    horarios=pd.read_excel('Horarios Entrega.XLSX', sheet_name='Sheet1', engine='openpyxl')
    return deliveries, horarios


def prepare_horarios(horarios):
    h=horarios.copy()
    h['cliente_key']=h['Deudor'].astype(str).str.replace('.0','',regex=False).str.strip()
    h['hora_inicio_min']=h['Horario inicia a'].apply(lambda x: parse_time_to_minutes(x, default=START_TIME_MIN))
    h['hora_fin_min']=h['Horario termina a'].apply(lambda x: parse_time_to_minutes(x, default=18*60))
    return h[['cliente_key','hora_inicio_min','hora_fin_min']].drop_duplicates('cliente_key')


def extract_clients(deliveries, horarios, fecha, ruta, label):
    df=deliveries.copy()
    df['FECHA_dt']=pd.to_datetime(df['FECHA'], errors='coerce', dayfirst=True)
    df['FECHA_str']=df['FECHA_dt'].dt.strftime('%Y-%m-%d')
    df['Ruta']=df['Ruta'].astype(str).str.strip()
    df['Población']=df['Población'].astype(str).str.strip()
    df['cliente_key']=df['Destinatario mcía..1'].astype(str).str.replace('.0','',regex=False).str.strip()
    df['cantidad']=pd.to_numeric(df['Cantidad entrega'], errors='coerce').fillna(0)
    route_lines=df[(df['FECHA_str']==fecha)&(df['Ruta']==ruta)].copy()
    if route_lines.empty:
        raise ValueError(f'No hi ha dades per {ruta} {fecha}')
    clients=route_lines.groupby('cliente_key').agg(
        nombre=('Nombre 1','first'), calle=('Calle','first'), cp=('CP','first'), poblacion=('Población','first'),
        piezas=('cantidad','sum'), lineas=('Material','size')
    ).reset_index()
    clients['cp']=clients['cp'].apply(clean_cp)
    clients['query_address']=clients.apply(build_address, axis=1)
    h=prepare_horarios(horarios)
    clients=clients.merge(h,on='cliente_key',how='left')
    clients['hora_inicio_min']=clients['hora_inicio_min'].fillna(START_TIME_MIN)
    clients['hora_fin_min']=clients['hora_fin_min'].fillna(18*60)
    clients['service_time_min']=PARKING_TIME_MIN + SERVICE_PER_PIECE_MIN*clients['piezas'] + SERVICE_PER_LINE_MIN*clients['lineas']
    clients['route_code']=ruta; clients['route_fecha']=fecha; clients['route_label']=label
    return clients, route_lines

# ==============================
# GEOCODING
# ==============================
def load_cache():
    if CACHE_FILE.exists(): return pd.read_csv(CACHE_FILE)
    return pd.DataFrame(columns=['address_key','query','lat','lng','display_name','status'])


def geocode_query(q):
    params={'q':q,'format':'json','limit':1,'countrycodes':'es'}
    headers={'User-Agent':USER_AGENT}
    try:
        r=requests.get(NOMINATIM_URL,params=params,headers=headers,timeout=15)
        if r.status_code!=200: return None,None,'',f'HTTP_{r.status_code}'
        data=r.json()
        if not data: return None,None,'','NO_ENCONTRADO'
        item=data[0]
        return float(item['lat']),float(item['lon']),item.get('display_name',''),'OK'
    except Exception as e:
        return None,None,'','ERROR_'+type(e).__name__


def geocode_all(clients):
    cache=load_cache()
    cache_map={row['address_key']:row for _,row in cache.iterrows()}
    rows=[]; new_rows=[]
    unique=clients[['query_address']].drop_duplicates().copy()
    unique['address_key']=unique['query_address'].apply(address_key)
    for _,a in unique.iterrows():
        key,q=a['address_key'],a['query_address']
        if key in cache_map:
            row=cache_map[key]
            rows.append({'address_key':key,'query':q,'lat':row.get('lat'),'lng':row.get('lng'),'display_name':row.get('display_name',''),'status':row.get('status','')})
        else:
            print('Geocodificant:',q)
            lat,lng,disp,status=geocode_query(q)
            row={'address_key':key,'query':q,'lat':lat,'lng':lng,'display_name':disp,'status':status}
            rows.append(row); new_rows.append(row)
            time.sleep(1.1)
    if new_rows:
        cache=pd.concat([cache,pd.DataFrame(new_rows)],ignore_index=True).drop_duplicates('address_key',keep='last')
        cache.to_csv(CACHE_FILE,index=False)
    geo=pd.DataFrame(rows).drop_duplicates('address_key')
    out=clients.copy()
    out['address_key']=out['query_address'].apply(address_key)
    out=out.merge(geo,on='address_key',how='left')
    out['lat']=pd.to_numeric(out['lat'],errors='coerce')
    out['lng']=pd.to_numeric(out['lng'],errors='coerce')
    out['coord_ok']=out['lat'].between(40.0,43.5)&out['lng'].between(0.0,4.0)
    out['geocode_valid']=out['status'].eq('OK')&out['coord_ok']
    out.to_csv(OUT/'geocoding_validacion.csv',index=False)
    return out

# ==============================
# STOP CLUSTERING
# ==============================
def time_windows_compatible(group):
    if not REQUIRE_TIME_WINDOW_OVERLAP:
        return True
    start=max([g['hora_inicio_min'] for g in group])
    end=min([g['hora_fin_min'] for g in group])
    return start <= end


def medoid_client(group):
    best=None; best_sum=1e18
    for cand in group:
        s=sum(distance_m(cand, other) for other in group)
        if s<best_sum:
            best_sum=s; best=cand
    return best


def build_stops(clients, clustered=True, radius_m=CLUSTER_RADIUS_M):
    records=[r.to_dict() for _,r in clients.iterrows()]
    if not clustered or radius_m<=0:
        stops=[]
        for i,r in enumerate(records):
            stops.append({
                'stop_id':f'S{i+1}', 'clients':[r], 'lat':r['lat'], 'lng':r['lng'], 'parking_client_key':r['cliente_key'],
                'piezas':r['piezas'], 'lineas':r['lineas'], 'hora_inicio_min':r['hora_inicio_min'], 'hora_fin_min':r['hora_fin_min'],
                'service_time_min':r['service_time_min'], 'walking_time_min':0.0, 'n_clients':1
            })
        return pd.DataFrame(stops)

    unassigned=set(range(len(records)))
    stops=[]
    while unassigned:
        # escollim primer el client amb finestra més urgent
        seed=min(unassigned, key=lambda i: records[i]['hora_fin_min'])
        group=[records[seed]]
        unassigned.remove(seed)
        # candidats propers al seed, ordenats per distància
        candidates=sorted(list(unassigned), key=lambda i: distance_m(records[seed], records[i]))
        for ci in candidates:
            if len(group)>=MAX_CLIENTS_PER_STOP: break
            cand=records[ci]
            if distance_m(records[seed], cand)>radius_m: continue
            tentative=group+[cand]
            if sum(g['piezas'] for g in tentative)>MAX_PIECES_PER_STOP: continue
            if not time_windows_compatible(tentative): continue
            # tots relativament propers al medoid candidat
            group=tentative
            unassigned.remove(ci)
        med=medoid_client(group)
        walking_m=sum(2*distance_m(med,g) for g in group if g['cliente_key']!=med['cliente_key'])
        walking_time=walking_m/WALK_SPEED_M_PER_MIN
        stops.append({
            'stop_id':f'S{len(stops)+1}', 'clients':group, 'lat':med['lat'], 'lng':med['lng'], 'parking_client_key':med['cliente_key'],
            'piezas':sum(g['piezas'] for g in group), 'lineas':sum(g['lineas'] for g in group),
            'hora_inicio_min':max(g['hora_inicio_min'] for g in group), 'hora_fin_min':min(g['hora_fin_min'] for g in group),
            'service_time_min':sum(g['service_time_min'] for g in group)+walking_time,
            'walking_time_min':walking_time, 'walking_m':walking_m, 'n_clients':len(group)
        })
    return pd.DataFrame(stops)

# ==============================
# ROUTE OPTIMIZATION ON STOPS
# ==============================
def greedy_stop_route(stops):
    pending=set(stops.index.tolist()); order=[]
    cur_lat,cur_lng=ORIGEN['lat'],ORIGEN['lng']; cur_time=START_TIME_MIN
    while pending:
        cand=[]
        for idx in pending:
            s=stops.loc[idx]
            dist=haversine_km(cur_lat,cur_lng,s['lat'],s['lng']); tt=travel_time_min(dist); arr=cur_time+tt
            late=max(0,arr-s['hora_fin_min']); urgency=max(0,s['hora_fin_min']-arr)/60
            score=ALPHA_TRAVEL*tt+BETA_LATE*late+GAMMA_URGENCY*urgency+DELTA_SERVICE*s['service_time_min']
            cand.append((score,idx,arr))
        _,idx,arr=sorted(cand,key=lambda x:x[0])[0]
        order.append(idx); pending.remove(idx)
        s=stops.loc[idx]
        cur_time=max(arr,s['hora_inicio_min'])+s['service_time_min']; cur_lat,cur_lng=s['lat'],s['lng']
    return order


def stop_route_cost(order, stops):
    cur_lat,cur_lng=ORIGEN['lat'],ORIGEN['lng']; cur_time=START_TIME_MIN
    dist_total=late_total=walk_total=0.0
    for idx in order:
        s=stops.loc[idx]
        dist=haversine_km(cur_lat,cur_lng,s['lat'],s['lng']); arr=cur_time+travel_time_min(dist)
        late_total+=max(0,arr-s['hora_fin_min']); dist_total+=dist; walk_total+=s['walking_time_min']
        cur_time=max(arr,s['hora_inicio_min'])+s['service_time_min']; cur_lat,cur_lng=s['lat'],s['lng']
    dist_total+=haversine_km(cur_lat,cur_lng,ORIGEN['lat'],ORIGEN['lng'])
    cost=COST_DISTANCE*dist_total+COST_LATE*late_total+COST_STOPS*len(order)+COST_WALKING*walk_total
    return cost,dist_total,late_total,walk_total


def two_opt_stops(order, stops, max_iter=200):
    best=order[:]; best_cost,_,best_late,_=stop_route_cost(best,stops)
    improved=True; it=0
    while improved and it<max_iter:
        improved=False; it+=1
        for i in range(0,len(best)-2):
            for j in range(i+2,len(best)):
                cand=best[:i]+list(reversed(best[i:j]))+best[j:]
                c,_,late,_=stop_route_cost(cand,stops)
                if c<best_cost and late<=best_late:
                    best,best_cost,best_late=cand,c,late; improved=True; break
            if improved: break
    return best


def validate_stop_route(order, stops, ruta, fecha, scenario):
    stop_rows=[]; client_rows=[]; cur_lat,cur_lng=ORIGEN['lat'],ORIGEN['lng']; cur_time=START_TIME_MIN; acc=0.0
    for stop_order,idx in enumerate(order,1):
        s=stops.loc[idx]
        dist=haversine_km(cur_lat,cur_lng,s['lat'],s['lng']); tt=travel_time_min(dist); arr=cur_time+tt
        wait=max(0,s['hora_inicio_min']-arr); late=max(0,arr-s['hora_fin_min'])
        dep=arr+wait+s['service_time_min']; acc+=dist
        stop_rows.append({'scenario':scenario,'route_code':ruta,'fecha':fecha,'stop_order':stop_order,'stop_id':s['stop_id'],'lat':s['lat'],'lng':s['lng'],'n_clients':s['n_clients'],'piezas':s['piezas'],'lineas':s['lineas'],'parking_client_key':s['parking_client_key'],'walking_time_min':round(s['walking_time_min'],1),'walking_m':round(s.get('walking_m',0),1),'hora_inicio_stop':hhmm(s['hora_inicio_min']),'hora_fin_stop':hhmm(s['hora_fin_min']),'travel_km':round(dist,3),'arrival_time':hhmm(arr),'departure_time':hhmm(dep),'late_minutes':round(late,1),'distance_accum_km':round(acc,3),'status':'TARDE' if late>0 else 'OK'})
        # ordre intern: primer el medoid/aparcament, després més propers
        clients=sorted(s['clients'], key=lambda c: distance_m({'lat':s['lat'],'lng':s['lng']}, c))
        for sub_i,c in enumerate(clients,1):
            client_rows.append({'scenario':scenario,'route_code':ruta,'fecha':fecha,'stop_order':stop_order,'sub_stop_order':sub_i,'stop_id':s['stop_id'],'cliente_key':c['cliente_key'],'nombre':c['nombre'],'direccion':c['query_address'],'lat':c['lat'],'lng':c['lng'],'piezas':c['piezas'],'lineas':c['lineas'],'is_parking_point':c['cliente_key']==s['parking_client_key']})
        cur_time=dep; cur_lat,cur_lng=s['lat'],s['lng']
    return pd.DataFrame(stop_rows), pd.DataFrame(client_rows)

# ==============================
# MAPS
# ==============================
def generate_cluster_map(stop_df, client_df, label, html_path):
    fig=go.Figure()
    points=[{'lat':ORIGEN['lat'],'lng':ORIGEN['lng'],'label':'ORIGEN'}]
    for _,r in stop_df.iterrows(): points.append({'lat':r['lat'],'lng':r['lng'],'label':f"S{int(r['stop_order'])}"})
    points.append({'lat':ORIGEN['lat'],'lng':ORIGEN['lng'],'label':'FIN'})
    coords=';'.join([f"{p['lng']},{p['lat']}" for p in points])
    try:
        res=requests.get(f'https://router.project-osrm.org/route/v1/driving/{coords}?overview=full&geometries=polyline',timeout=15).json()
        path=polyline.decode(res['routes'][0]['geometry']); lats,lons=zip(*path)
        fig.add_trace(go.Scattermapbox(lat=lats,lon=lons,mode='lines',line=dict(width=4,color='#004B87'),name='Ruta camió OSRM'))
    except Exception:
        fig.add_trace(go.Scattermapbox(lat=[p['lat'] for p in points],lon=[p['lng'] for p in points],mode='lines',line=dict(width=4,color='#004B87'),name='Ruta camió visual'))

    # línies caminant dins de cada parada agrupada
    for _,s in stop_df.iterrows():
        sub=client_df[client_df['stop_id']==s['stop_id']]
        for _,c in sub.iterrows():
            if not c['is_parking_point']:
                fig.add_trace(go.Scattermapbox(lat=[s['lat'],c['lat']],lon=[s['lng'],c['lng']],mode='lines',line=dict(width=2,color='gray'),hoverinfo='skip',showlegend=False))

    # clients petits
    fig.add_trace(go.Scattermapbox(
        lat=client_df['lat'], lon=client_df['lng'], mode='markers+text',
        marker=dict(size=7,color='#E2231A'),
        text=[f"{int(r.stop_order)}.{int(r.sub_stop_order)}" for _,r in client_df.iterrows()],
        textposition='bottom right',
        hovertext=[f"<b>{r.nombre}</b><br>{r.direccion}<br>Parada S{int(r.stop_order)}" for _,r in client_df.iterrows()],
        hoverinfo='text', name='Locals'
    ))
    # parades grans
    fig.add_trace(go.Scattermapbox(
        lat=stop_df['lat'], lon=stop_df['lng'], mode='markers+text',
        marker=dict(size=15,color='#004B87'),
        text=[f"S{int(r.stop_order)}" for _,r in stop_df.iterrows()],
        textposition='top right',
        hovertext=[f"<b>S{int(r.stop_order)}</b><br>{int(r.n_clients)} locals<br>Walking: {r.walking_time_min} min<br>Status: {r.status}" for _,r in stop_df.iterrows()],
        hoverinfo='text', name='Parades camió'
    ))
    center_lat=np.mean(list(stop_df['lat'])+[ORIGEN['lat']]); center_lng=np.mean(list(stop_df['lng'])+[ORIGEN['lng']])
    fig.update_layout(mapbox=dict(style='carto-positron',center=dict(lat=center_lat,lon=center_lng),zoom=12.5),margin={'r':0,'t':75,'l':0,'b':0},title=f"<b>{label}</b><br><sup>Parades agrupades: S = parada camió, x.y = local dins parada</sup>",width=1100,height=800)
    fig.write_html(html_path)
    return fig

# ==============================
# RUN
# ==============================
def run_clustering_optimizer():
    deliveries,horarios=load_files()
    all_clients=[]; route_lines={}
    for cfg in DEMO_ROUTES:
        c,l=extract_clients(deliveries,horarios,cfg['fecha'],cfg['ruta'],cfg['label'])
        all_clients.append(c); route_lines[(cfg['fecha'],cfg['ruta'])]=l
    all_geo=geocode_all(pd.concat(all_clients,ignore_index=True))
    summary=[]
    for cfg in DEMO_ROUTES:
        fecha,ruta,label=cfg['fecha'],cfg['ruta'],cfg['label']
        cr=all_geo[(all_geo['route_fecha']==fecha)&(all_geo['route_code']==ruta)].copy()
        valid=cr[cr['geocode_valid']].copy().reset_index(drop=True)
        invalid=cr[~cr['geocode_valid']].copy()
        if valid.empty: raise ValueError(f'Cap client geocodificat vàlid per {ruta} {fecha}')

        # baseline: 1 client = 1 parada
        base_stops=build_stops(valid,clustered=False)
        base_order=two_opt_stops(greedy_stop_route(base_stops),base_stops)
        base_stop_df,base_client_df=validate_stop_route(base_order,base_stops,ruta,fecha,'baseline')
        base_cost,base_km,base_late,base_walk=stop_route_cost(base_order,base_stops)

        # clustered: clients propers en 1 parada
        cl_stops=build_stops(valid,clustered=True,radius_m=CLUSTER_RADIUS_M)
        cl_order=two_opt_stops(greedy_stop_route(cl_stops),cl_stops)
        cl_stop_df,cl_client_df=validate_stop_route(cl_order,cl_stops,ruta,fecha,'clustered')
        cl_cost,cl_km,cl_late,cl_walk=stop_route_cost(cl_order,cl_stops)

        # decisió automàtica: només usem clustering si millora cost i no empitjora retards
        use_clustered=(cl_cost<base_cost) and (cl_late<=base_late+1e-6)
        chosen='clustered' if use_clustered else 'baseline'
        stop_df=cl_stop_df if use_clustered else base_stop_df
        client_df=cl_client_df if use_clustered else base_client_df
        cost=cl_cost if use_clustered else base_cost

        stem=f'{ruta}_{fecha}'
        base_stop_df.to_csv(OUT/f'{stem}_baseline_parades.csv',index=False)
        base_client_df.to_csv(OUT/f'{stem}_baseline_clients.csv',index=False)
        cl_stop_df.to_csv(OUT/f'{stem}_clustered_parades.csv',index=False)
        cl_client_df.to_csv(OUT/f'{stem}_clustered_clients.csv',index=False)
        stop_df.to_csv(OUT/f'{stem}_BEST_parades.csv',index=False)
        client_df.to_csv(OUT/f'{stem}_BEST_clients.csv',index=False)
        invalid.to_csv(OUT/f'{stem}_clients_sense_geocodificar.csv',index=False)
        generate_cluster_map(stop_df,client_df,f'{label} | {ruta} | {fecha} | BEST={chosen}',OUT/f'{stem}_mapa_cluster.html')

        summary.append({'fecha':fecha,'ruta':ruta,'label':label,'clients_total':len(cr),'clients_geocoded':len(valid),'clients_no_geo':len(invalid),'baseline_stops':len(base_stops),'clustered_stops':len(cl_stops),'best_mode':chosen,'best_stops':len(stop_df),'baseline_cost':round(base_cost,2),'clustered_cost':round(cl_cost,2),'best_cost':round(cost,2),'baseline_km':round(base_km,2),'clustered_km':round(cl_km,2),'baseline_late_min':round(base_late,1),'clustered_late_min':round(cl_late,1),'clustered_walking_min':round(cl_walk,1),'mapa':str(OUT/f'{stem}_mapa_cluster.html')})
        print(f'{stem}: baseline={len(base_stops)} parades, clustered={len(cl_stops)} parades, BEST={chosen}')

    res=pd.DataFrame(summary)
    res.to_csv(OUT/'resumen_cluster_vs_baseline.csv',index=False)
    with pd.ExcelWriter(OUT/'resumen_cluster_vs_baseline.xlsx',engine='openpyxl') as w:
        res.to_excel(w,sheet_name='resumen',index=False)
        all_geo.to_excel(w,sheet_name='geocoding',index=False)
    with zipfile.ZipFile('mapes_rutes_cluster_resultats.zip','w',zipfile.ZIP_DEFLATED) as z:
        for p in OUT.glob('*'): z.write(p,arcname=p.name)
    print('ZIP creat: mapes_rutes_cluster_resultats.zip')
    return res


def mostrar_mapa_cluster(ruta='DR0006',fecha='2026-03-04'):
    path=OUT/f'{ruta}_{fecha}_mapa_cluster.html'
    if not path.exists(): raise FileNotFoundError(f'No existeix {path}. Executa summary_cluster = run_clustering_optimizer()')
    display(IFrame(str(path),width=1100,height=800))

summary_cluster=run_clustering_optimizer()
summary_cluster



"""## Veure mapes agrupats

"""

# PATCH VISUAL: mostrar tots els locals i totes les parades
# Aquest patch substitueix generate_cluster_map.
# No canvia l'algorisme, només arregla la visualització.

import math
import numpy as np
import plotly.graph_objects as go
import requests
import polyline

VISUAL_OFFSET_M = 12  # només visual; no modifica coordenades reals ni CSVs


def _offset_latlng(lat, lng, meters, angle_rad):
    dlat = (meters * math.sin(angle_rad)) / 111_320
    dlng = (meters * math.cos(angle_rad)) / (111_320 * math.cos(math.radians(lat)))
    return lat + dlat, lng + dlng


def generate_cluster_map(stop_df, client_df, label, html_path):
    fig = go.Figure()

    # Ruta del camió: origen -> parades -> origen
    points = [{'lat': ORIGEN['lat'], 'lng': ORIGEN['lng'], 'label': 'ORIGEN'}]

    for _, r in stop_df.sort_values('stop_order').iterrows():
        points.append({
            'lat': r['lat'],
            'lng': r['lng'],
            'label': f"S{int(r['stop_order'])}"
        })

    points.append({
        'lat': ORIGEN['lat'],
        'lng': ORIGEN['lng'],
        'label': 'FIN'
    })

    coords = ';'.join([f"{p['lng']},{p['lat']}" for p in points])

    try:
        res = requests.get(
            f"https://router.project-osrm.org/route/v1/driving/{coords}?overview=full&geometries=polyline",
            timeout=15
        ).json()

        path = polyline.decode(res['routes'][0]['geometry'])
        lats, lons = zip(*path)

        fig.add_trace(go.Scattermapbox(
            lat=lats,
            lon=lons,
            mode='lines',
            line=dict(width=4, color='#004B87'),
            name='Ruta camió OSRM'
        ))

    except Exception:
        fig.add_trace(go.Scattermapbox(
            lat=[p['lat'] for p in points],
            lon=[p['lng'] for p in points],
            mode='lines',
            line=dict(width=4, color='#004B87'),
            name='Ruta camió visual'
        ))

    # Copiem els locals per aplicar offset només visual
    client_plot = client_df.copy().sort_values(
        ['stop_order', 'sub_stop_order']
    ).reset_index(drop=True)

    plot_lats = []
    plot_lngs = []

    for _, c in client_plot.iterrows():
        siblings = client_plot[client_plot['stop_id'] == c['stop_id']]
        n = max(1, len(siblings))
        k = int(c['sub_stop_order']) - 1

        angle = 2 * math.pi * k / n

        lat_v, lng_v = _offset_latlng(
            float(c['lat']),
            float(c['lng']),
            VISUAL_OFFSET_M,
            angle
        )

        plot_lats.append(lat_v)
        plot_lngs.append(lng_v)

    client_plot['plot_lat'] = plot_lats
    client_plot['plot_lng'] = plot_lngs

    # Línies grises parada -> local
    for _, s in stop_df.iterrows():
        sub = client_plot[client_plot['stop_id'] == s['stop_id']]

        for _, c in sub.iterrows():
            fig.add_trace(go.Scattermapbox(
                lat=[s['lat'], c['plot_lat']],
                lon=[s['lng'], c['plot_lng']],
                mode='lines',
                line=dict(width=1, color='gray'),
                hoverinfo='skip',
                showlegend=False
            ))

    # Parades del camió, en blau
    fig.add_trace(go.Scattermapbox(
        lat=stop_df['lat'],
        lon=stop_df['lng'],
        mode='markers+text',
        marker=dict(size=18, color='#004B87', opacity=0.65),
        text=[f"S{int(r.stop_order)}" for _, r in stop_df.iterrows()],
        textposition='top right',
        hovertext=[
            f"<b>Parada camió S{int(r.stop_order)}</b><br>"
            f"Locals en aquesta parada: {int(r.n_clients)}<br>"
            f"Peces totals: {int(r.piezas)}<br>"
            f"Walking: {r.walking_time_min} min<br>"
            f"Status: {r.status}"
            for _, r in stop_df.iterrows()
        ],
        hoverinfo='text',
        name='Parades camió'
    ))

    # Locals, en vermell, dibuixats DESPRÉS perquè quedin per sobre
    fig.add_trace(go.Scattermapbox(
        lat=client_plot['plot_lat'],
        lon=client_plot['plot_lng'],
        mode='markers+text',
        marker=dict(size=10, color='#E2231A', opacity=0.95),
        text=[
            f"{int(r.stop_order)}.{int(r.sub_stop_order)}"
            for _, r in client_plot.iterrows()
        ],
        textposition='bottom right',
        hovertext=[
            f"<b>Local {int(r.stop_order)}.{int(r.sub_stop_order)}</b><br>"
            f"{r.nombre}<br>"
            f"{r.direccion}<br>"
            f"Parada camió: S{int(r.stop_order)}<br>"
            f"Peces: {int(r.piezas)} | Línies: {int(r.lineas)}"
            for _, r in client_plot.iterrows()
        ],
        hoverinfo='text',
        name='Locals / establiments'
    ))

    # Origen
    fig.add_trace(go.Scattermapbox(
        lat=[ORIGEN['lat']],
        lon=[ORIGEN['lng']],
        mode='markers+text',
        marker=dict(size=15, color='black'),
        text=['ORIGEN'],
        textposition='top left',
        hovertext=['DDI Fàbrica Mollet'],
        hoverinfo='text',
        name='Origen'
    ))

    center_lat = np.mean(list(stop_df['lat']) + [ORIGEN['lat']])
    center_lng = np.mean(list(stop_df['lng']) + [ORIGEN['lng']])

    n_clients = len(client_plot)
    n_stops = len(stop_df)

    fig.update_layout(
        mapbox=dict(
            style='carto-positron',
            center=dict(lat=center_lat, lon=center_lng),
            zoom=12.5
        ),
        margin={'r': 0, 't': 85, 'l': 0, 'b': 0},
        title=(
            f"<b>{label}</b><br>"
            f"<sup>{n_stops} parades de camió | {n_clients} locals representats | "
            f"S = parada, x.y = local dins parada</sup>"
        ),
        width=1100,
        height=820,
    )

    fig.write_html(html_path)
    return fig


print("Patch aplicat: ara el mapa hauria de mostrar tots els locals i totes les parades.")

# mostrar_mapa_cluster('DR0006','2026-03-04')
# mostrar_mapa_cluster('DR0017','2026-03-11')
# mostrar_mapa_cluster('DR0038','2026-03-30')

"""## Descarregar resultats

"""

from google.colab import files
files.download('mapes_rutes_cluster_resultats.zip')